[package]
name = "file_encrypt"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
actix-files = "0.6.6"
actix-multipart = "0.6.1"
serde = { version = "1.0.217", features = ["derive"] }
futures-util = "0.3.31"
